version: "3"
services: 
  catalog-service: 
      build:
        context: .
        dockerfile: catalogservice/Dockerfile
      container_name: docker-catalogservice
      depends_on: 
        - mysql-service
      environment: 
        WAIT_HOSTS: "mysql:3306"
        WAIT_HOSTS_TIMEOUT: 300
        WAIT_SLEEP_INTERVAL: 30
        WAIT_HOST_CONNECT_TIMEOUT: 30
    
      image: catalogservice
      ports: 
        - "10555:9000"
      restart: on-failure
      networks:
        - networkIdruide
  mysql-service: 
      container_name: docker-mysql
      environment: 
        MYSQL_DABATASE: idrivedb
        MYSQL_ROOT_HOST: "%"
        MYSQL_ROOT_PASSWORD: admincc
      healthcheck: 
        interval: 4s
        retries: 5
        test: "/usr/bin/mysql --user=root --password=admin --execute \\\"SHOW DATABASES\" "
        timeout: 20s
      image: mysql
      ports: 
        - "6666:3306"
      restart: always
      volumes: 
        - "./sql:/docker-entrypoint-initdb.d"
      networks:
        networkIdruide:
          aliases:
           - mysql-service
  order-service:
     build:
       context: .
       dockerfile: orderservice/Dockerfile 
     container_name: docker-orderservice
     environment: 
       WAIT_HOSTS: "mysql:3306"
       WAIT_HOSTS_TIMEOUT: 300
       WAIT_SLEEP_INTERVAL: 30
       WAIT_HOST_CONNECT_TIMEOUT: 30
     depends_on: 
         - mysql-service
     image: orderservice
     ports: 
       - "10444:8000"
     restart: on-failure
     networks:
       - networkIdruide
  packing-service:
    build:
      context: .
      dockerfile: packingservice/Dockerfile 
    container_name: docker-packingservice
    environment: 
      WAIT_HOSTS: "mysql:3306"
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    depends_on: 
        - mysql-service 
    image: packingservice
    ports: 
      - "10333:7000"
    restart: on-failure
    networks:
      - networkIdruide
  zookeeper:
        image: confluentinc/cp-zookeeper
        ports:
          - 2181:2181
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ALLOW_ANONYMOUS_LOGIN: "yes"
        container_name: zookeeper
        networks:
          networkIdruide:
            aliases:
             - zookeeper
  kafka:
       image: confluentinc/cp-kafka
       container_name: kafka
       ports:
          - 9092:9092
       environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPIC: "topicstock:1:3,topicdelivery:1:3"
          KAFKA_BROKER_ID: 1
          ALLOW_PLAINTEXT_LISTENER: "yes"
          KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://:9092
       networks:
          - networkIdruide
       volumes:
          - /var/run/docker.sock:/var/run/docker.sock
       depends_on:
          - zookeeper
networks:
      networkIdruide:  