graphql:
  servlet:
    mapping: /order
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /order
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false

spring:
  kafka:
    producer:
      bootstarp-servers: locahost:2181
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer